# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/logrusorgru/aurora"
  version = "v2.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/ryanuber/columnize"
  version = "v2.1.0"
 
[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"
