version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch

    working_directory: /go/src/github.com/ironstar-io/tokaido

    steps:
      - checkout     

      - run: dep ensure

      - run: make build-windows
      - run: make build-linux
      - run: make build-osx
      - run: ls dist/

      - store_artifacts:
          path: /go/src/github.com/ironstar-io/tokaido/dist/
          destination: artifacts

      - persist_to_workspace:        
          root: /go/src/github.com/ironstar-io/tokaido/
          paths: 
            - dist

  release-edge:
    docker:
      - image: circleci/golang:1.10-stretch
    environment:
      VERSION: edge            
    steps:
      - attach_workspace:
          at: ./
      - run: go get github.com/tcnksm/ghr          
      - run:
          name: "Publish Linux Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ironstar-io -r tokaido -b "The latest (unstable) build of the Tokaido CLI. Please use a numbered release if you need a stable Tokaido environment." -c ${CIRCLE_SHA1} -prerelease -delete ${VERSION} ./dist/

  release-stable:
    docker:
      - image: circleci/golang:1.10-stretch        
    steps:
      - attach_workspace:
          at: ./
      - run: go get github.com/tcnksm/ghr          
      - run: echo tag = ${CIRCLE_TAG}
      - run:
          name: "Publish Linux Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ironstar-io -r tokaido -b "Please your change log here" -c ${CIRCLE_SHA1} -draft -prerelease -delete ${CIRCLE_TAG} ./dist/

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
      - release-edge:
          requires: 
            - build
          filters:
            branches:
              only:               
                - develop
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+.\d+.\d+$/
      - release-stable:
          requires: 
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+.\d+.\d+$/
